export const CAMPAIGN_SAVE_KEY = 'skybreak-campaign-v1';
export const LEGACY_PROGRESS_KEY = 'skybreak-progress-v2';

export const UPGRADE_DEFINITIONS = [
  {
    id: 'armor',
    title: 'Armor Plating',
    body: 'Layered desert alloy increases maximum hull.',
    tiers: [
      { cost: 120, maxHullBonus: 12 },
      { cost: 220, maxHullBonus: 24 },
      { cost: 340, maxHullBonus: 38 }
    ]
  },
  {
    id: 'capacitor',
    title: 'Capacitor',
    body: 'A hotter charge bus trims cannon cooldown.',
    tiers: [
      { cost: 110, fireDelayMultiplier: 0.94 },
      { cost: 210, fireDelayMultiplier: 0.88 },
      { cost: 320, fireDelayMultiplier: 0.82 }
    ]
  },
  {
    id: 'guidance',
    title: 'Guidance',
    body: 'Recovered alien glass improves assisted shell tracking.',
    tiers: [
      { cost: 130, guidanceBonus: 0.025, hitAssistBonus: 0.45 },
      { cost: 240, guidanceBonus: 0.05, hitAssistBonus: 0.9 },
      { cost: 360, guidanceBonus: 0.08, hitAssistBonus: 1.35 }
    ]
  },
  {
    id: 'fieldRepair',
    title: 'Field Repair',
    body: 'Better repair crews restore more hull between missions.',
    tiers: [
      { cost: 100, repairBonus: 8 },
      { cost: 190, repairBonus: 16 },
      { cost: 280, repairBonus: 26 }
    ]
  }
];

const baseSpeakers = {
  ops: 'Ops',
  vega: 'Vega',
  rook: 'Rook',
  atlas: 'Atlas',
  echo: 'Echo'
};

const briefing = (speaker, body) => ({ speaker, body });
const debrief = (success, failure) => ({ success, failure });
const rewards = (salvage) => ({ salvage });
const radio = (id, trigger, speaker, title, body, extra = {}) => ({ id, trigger, speaker, title, body, ...extra });

export const CAMPAIGN_MISSIONS = [
  {
    id: 'training-range',
    campaignIndex: 0,
    act: 'Act I: First Contact',
    title: 'Mission 1: Training Range',
    mapName: 'Amber Range',
    objective: 'Destroy 4 scout UFOs.',
    intro: 'Four slow scouts, generous aim assist, and only one target overhead at a time.',
    success: 'Range clear. Radar crew has opened the salt-flat relay road.',
    briefing: briefing('Ops', 'Amber Range is quiet until the radar starts drawing circles in the sky. Roll out, confirm contact, and knock down anything that refuses to identify itself.'),
    debrief: debrief('First contact confirmed. The scouts were probing for weak ground relays, and Skybreak is now officially awake.', 'The scouts slipped the net and mapped our response time. Reset the range and make the next pass count.'),
    speakers: baseSpeakers,
    rewards: rewards(150),
    unlockText: 'Salt Relay opens on the campaign route.',
    radioEvents: [
      radio('m1-start', 'start', 'Ops', 'Radar contact', 'Four saucers crossing Amber Range. Keep the cannon warm.'),
      radio('m1-first-kill', 'kills', 'Rook', 'Clean hit', 'That shell burst right under the saucer. Do that three more times.', { count: 1 }),
      radio('m1-low-hull', 'hull', 'Vega', 'Hull warning', 'Their beams are hotter than the readout says. Move through the attack line.', { below: 55 })
    ],
    worldSize: 92,
    ufoLimit: 52,
    cameraHeight: 24,
    cameraDistance: 32,
    sky: 0x1b2630,
    fog: 0x9b8060,
    fogDensity: 0.011,
    ground: 0xb98b4f,
    groundDark: 0x8e6b42,
    scrub: 0x4a6a54,
    ridge: 0x6e5547,
    accent: 0xf3bd55,
    rocks: 38,
    cactus: 14,
    ridges: 14,
    extras: 'runway',
    objectiveType: 'destroy',
    destroyTarget: 4,
    ufoTotal: 4,
    maxActive: 1,
    spawnDelay: [1.6, 2.35],
    firstSpawn: 0.45,
    speed: [3.8, 5.1],
    altitude: [9.8, 15.5],
    drift: 0.55,
    hitAssist: 4.9,
    shellSpeed: 42,
    fireDelay: 0.2,
    beamDamage: 1.9,
    escapeDamage: 2.5,
    score: 150,
    maxUfoHp: 1,
    ufoMix: [{ type: 'scout', weight: 1 }]
  },
  {
    id: 'relay-defense',
    campaignIndex: 1,
    act: 'Act I: First Contact',
    title: 'Mission 2: Salt Relay',
    mapName: 'Salt Relay',
    objective: 'Destroy 7 UFOs while at least one relay tower survives.',
    intro: 'The saucers will try to burn down the relay towers. Break their attack runs.',
    success: 'Relay held. The ridge network is back online.',
    briefing: briefing('Vega', 'The scouts found our relay spine. Three towers keep the north grid talking; lose them and every later mission goes blind.'),
    debrief: debrief('The relay held. The invaders now know Skybreak can defend fixed targets.', 'Without a tower online, the ridge network goes dark. Rebuild the defense pattern.'),
    speakers: baseSpeakers,
    rewards: rewards(190),
    unlockText: 'Cobalt Canyon signal trace unlocked.',
    radioEvents: [
      radio('m2-start', 'start', 'Vega', 'Relay defense', 'Protect the towers. Bombers will loiter when they find a target.'),
      radio('m2-three-kills', 'kills', 'Ops', 'Pattern read', 'They are turning toward whichever tower still broadcasts. Cut them off early.', { count: 3 }),
      radio('m2-tower-risk', 'objective', 'Atlas', 'Tower damage', 'Relay integrity is sliding. Intercept the beaming saucer now.', { key: 'towerDamaged' })
    ],
    worldSize: 110,
    ufoLimit: 63,
    cameraHeight: 25,
    cameraDistance: 35,
    sky: 0x182830,
    fog: 0x8fa7a0,
    fogDensity: 0.012,
    ground: 0xa4a58f,
    groundDark: 0x6f7f79,
    scrub: 0x3e6c64,
    ridge: 0x596765,
    accent: 0x7de0c5,
    rocks: 42,
    cactus: 8,
    ridges: 16,
    extras: 'relays',
    objectiveType: 'protect',
    destroyTarget: 7,
    ufoTotal: 8,
    maxActive: 2,
    spawnDelay: [1.75, 2.65],
    firstSpawn: 0.7,
    speed: [4.8, 6.9],
    altitude: [10.5, 17.5],
    drift: 1.2,
    hitAssist: 3.8,
    shellSpeed: 41,
    fireDelay: 0.24,
    beamDamage: 2.9,
    towerDamage: 7.2,
    escapeDamage: 4,
    score: 190,
    maxUfoHp: 1,
    ufoMix: [
      { type: 'scout', weight: 3 },
      { type: 'raider', weight: 2 },
      { type: 'bomber', weight: 1 }
    ]
  },
  {
    id: 'night-canyon',
    campaignIndex: 2,
    act: 'Act I: First Contact',
    title: 'Mission 3: Cobalt Canyon',
    mapName: 'Cobalt Canyon',
    objective: 'Survive 75 seconds and destroy 9 raiders.',
    intro: 'A longer canyon push with skimmers that weave across your aim line.',
    success: 'Canyon sky is clear. Storm front coordinates received.',
    briefing: briefing('Echo', 'The relay caught a signal bouncing through Cobalt Canyon. It is not a message; it is a map. Survive the trace long enough to learn where it points.'),
    debrief: debrief('The signal points to a storm corridor over the atoll. Whatever commands the scouts is moving closer.', 'The signal broke before we copied the coordinates. Run the canyon again.'),
    speakers: baseSpeakers,
    rewards: rewards(230),
    unlockText: 'Storm Atoll route plotted.',
    radioEvents: [
      radio('m3-start', 'start', 'Echo', 'Signal trace', 'Cobalt Canyon is live. Skimmers will weave; lead the shot.'),
      radio('m3-time', 'time', 'Ops', 'Half trace', 'Thirty seconds of signal copied. Keep the tank intact.', { at: 35 }),
      radio('m3-kills', 'kills', 'Rook', 'Skimmer down', 'They move weird, but they still burn.', { count: 4 })
    ],
    worldSize: 126,
    ufoLimit: 72,
    cameraHeight: 27,
    cameraDistance: 38,
    sky: 0x101923,
    fog: 0x27324a,
    fogDensity: 0.016,
    ground: 0x5d5e6a,
    groundDark: 0x3d4253,
    scrub: 0x315c61,
    ridge: 0x282d3d,
    accent: 0x9fc7ff,
    rocks: 54,
    cactus: 5,
    ridges: 24,
    extras: 'beacons',
    objectiveType: 'survive',
    destroyTarget: 9,
    survivalTime: 75,
    ufoTotal: 12,
    maxActive: 2,
    spawnDelay: [1.55, 2.25],
    firstSpawn: 0.7,
    speed: [5.9, 8.1],
    altitude: [12, 20],
    drift: 1.6,
    hitAssist: 3.4,
    shellSpeed: 42,
    fireDelay: 0.23,
    beamDamage: 3.25,
    escapeDamage: 5,
    score: 230,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'raider', weight: 3 },
      { type: 'zigzag', weight: 3 },
      { type: 'shield', weight: 1 }
    ]
  },
  {
    id: 'storm-atoll',
    campaignIndex: 3,
    act: 'Act II: The Signal War',
    title: 'Mission 4: Storm Atoll',
    mapName: 'Storm Atoll',
    objective: 'Destroy 11 UFOs before the storm corridor closes.',
    intro: 'Wide open map. Skimmers swing laterally and bombers make slow, dangerous beam runs.',
    success: 'Atoll corridor is open. Mothership gate is exposed.',
    briefing: briefing('Ops', 'A storm cell is hiding a saucer lane. Punch through before the corridor seals and we can follow the carrier wake.'),
    debrief: debrief('The storm corridor is open. Debris from a larger craft is falling near Glass Flats.', 'The corridor closed before we broke their line. We need another run before the trail goes cold.'),
    speakers: baseSpeakers,
    rewards: rewards(275),
    unlockText: 'Glass Flats recovery operation unlocked.',
    radioEvents: [
      radio('m4-start', 'start', 'Ops', 'Storm window', 'The corridor closes fast. Every saucer down buys us a cleaner path.'),
      radio('m4-timer', 'time', 'Vega', 'Storm pressure', 'The storm wall is folding in. Do not chase stragglers too far.', { at: 70 }),
      radio('m4-kills', 'kills', 'Rook', 'Corridor cracking', 'Their formation is breaking. Push through.', { count: 7 })
    ],
    worldSize: 144,
    ufoLimit: 84,
    cameraHeight: 29,
    cameraDistance: 42,
    sky: 0x17232f,
    fog: 0x547b86,
    fogDensity: 0.013,
    ground: 0x7b8063,
    groundDark: 0x53635c,
    scrub: 0x2f6f62,
    ridge: 0x3f565b,
    accent: 0x7de0c5,
    rocks: 58,
    cactus: 4,
    ridges: 22,
    extras: 'storm',
    objectiveType: 'destroy',
    destroyTarget: 11,
    ufoTotal: 13,
    maxActive: 3,
    spawnDelay: [1.4, 2.1],
    firstSpawn: 0.75,
    speed: [6.2, 8.4],
    altitude: [12.5, 22],
    drift: 1.95,
    hitAssist: 3.1,
    shellSpeed: 43,
    fireDelay: 0.22,
    beamDamage: 3.45,
    escapeDamage: 5.2,
    score: 275,
    maxUfoHp: 2,
    timeLimit: 115,
    ufoMix: [
      { type: 'zigzag', weight: 4 },
      { type: 'raider', weight: 3 },
      { type: 'bomber', weight: 2 },
      { type: 'shield', weight: 1 }
    ]
  },
  {
    id: 'glass-flats',
    campaignIndex: 4,
    act: 'Act II: The Signal War',
    title: 'Mission 5: Glass Flats',
    mapName: 'Glass Flats',
    objective: 'Recover 3 alien cores and return them to the pad.',
    intro: 'Drive into the flats, collect glowing cores, and return each one while raiders circle overhead.',
    success: 'Alien cores recovered. Hangar crews can turn the glass into guidance upgrades.',
    briefing: briefing('Vega', 'A carrier shed three glass cores over the flats. They are still broadcasting. Touch each core, haul it back to the pad, and keep the sky clear.'),
    debrief: debrief('The cores are ours. Guidance teams are already arguing over who gets the first shard.', 'The cores kept broadcasting until the saucers reclaimed the site. We need those shards.'),
    speakers: baseSpeakers,
    rewards: rewards(320),
    unlockText: 'Red Basin Decoy authorized.',
    radioEvents: [
      radio('m5-start', 'start', 'Vega', 'Recovery run', 'Pick up a core and return to the pad. Do not let the glow distract you.'),
      radio('m5-first-core', 'objective', 'Echo', 'Core secured', 'That shard is singing through every channel we have.', { key: 'collectOne' }),
      radio('m5-all-core', 'objective', 'Ops', 'Payload complete', 'All cores recovered. Clear remaining contacts.', { key: 'collectAll' })
    ],
    worldSize: 132,
    ufoLimit: 76,
    cameraHeight: 28,
    cameraDistance: 39,
    sky: 0x1b2025,
    fog: 0xb5a88a,
    fogDensity: 0.012,
    ground: 0xc4b277,
    groundDark: 0x7e7457,
    scrub: 0x4e705a,
    ridge: 0x6a665f,
    accent: 0xf7d879,
    rocks: 46,
    cactus: 7,
    ridges: 18,
    extras: 'glass',
    objectiveType: 'collect',
    objectiveScript: { total: 3, pickupRadius: 4.4, returnRadius: 9 },
    destroyTarget: 6,
    ufoTotal: 9,
    maxActive: 2,
    spawnDelay: [1.55, 2.4],
    firstSpawn: 0.65,
    speed: [5.8, 7.8],
    altitude: [11, 19],
    drift: 1.6,
    hitAssist: 3.4,
    shellSpeed: 42,
    fireDelay: 0.22,
    beamDamage: 3.15,
    escapeDamage: 4.5,
    score: 260,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'raider', weight: 4 },
      { type: 'zigzag', weight: 2 },
      { type: 'shield', weight: 1 }
    ]
  },
  {
    id: 'red-basin-decoy',
    campaignIndex: 5,
    act: 'Act II: The Signal War',
    title: 'Mission 6: Red Basin Decoy',
    mapName: 'Red Basin',
    objective: 'Hold the decoy beacon for 80 seconds and destroy 10 UFOs.',
    intro: 'The beacon pulls saucers toward you. Stay near it to keep the decoy broadcasting.',
    success: 'Decoy worked. Carrier telemetry exposed a hunting path over Iron Mesa.',
    briefing: briefing('Atlas', 'We built a fake command post out of spare radios and optimism. Park near the decoy beacon so it keeps broadcasting, then punish everything that answers.'),
    debrief: debrief('The decoy fooled them. A carrier peeled away from the fleet and is crossing Iron Mesa alone.', 'The decoy failed before the carrier committed. Reset the beacon and bait the hook again.'),
    speakers: baseSpeakers,
    rewards: rewards(360),
    unlockText: 'Iron Mesa carrier hunt unlocked.',
    radioEvents: [
      radio('m6-start', 'start', 'Atlas', 'Decoy live', 'Stay close to the beacon. If the signal drops, they will know it is bait.'),
      radio('m6-hold', 'objective', 'Vega', 'Signal strong', 'Beacon draw is stable. They are taking the bait.', { key: 'activateHalf' }),
      radio('m6-kills', 'kills', 'Rook', 'Crowded sky', 'The decoy is popular. Try not to be.', { count: 6 })
    ],
    worldSize: 138,
    ufoLimit: 82,
    cameraHeight: 28,
    cameraDistance: 40,
    sky: 0x251a19,
    fog: 0x9d5542,
    fogDensity: 0.014,
    ground: 0x9f6044,
    groundDark: 0x663a31,
    scrub: 0x4d6247,
    ridge: 0x5b3530,
    accent: 0xff9a58,
    rocks: 60,
    cactus: 10,
    ridges: 20,
    extras: 'decoy',
    objectiveType: 'activate',
    objectiveScript: { nodes: 1, holdTime: 80, radius: 11, requireContinuous: false },
    destroyTarget: 10,
    ufoTotal: 13,
    maxActive: 3,
    spawnDelay: [1.35, 2.05],
    firstSpawn: 0.6,
    speed: [6.2, 8.6],
    altitude: [11.5, 21],
    drift: 1.9,
    hitAssist: 3.05,
    shellSpeed: 43,
    fireDelay: 0.22,
    beamDamage: 3.35,
    escapeDamage: 5,
    score: 285,
    maxUfoHp: 2,
    survivalTime: 80,
    ufoMix: [
      { type: 'raider', weight: 4 },
      { type: 'zigzag', weight: 3 },
      { type: 'bomber', weight: 2 },
      { type: 'shield', weight: 1 }
    ]
  },
  {
    id: 'iron-mesa',
    campaignIndex: 6,
    act: 'Act II: The Signal War',
    title: 'Mission 7: Iron Mesa',
    mapName: 'Iron Mesa',
    objective: 'Destroy the carrier escort and bring down the carrier.',
    intro: 'First carrier contact. Its shielded hull takes repeated hits and pulls escorts toward the mesa.',
    success: 'Carrier down. Its wake points straight into the blackout field.',
    briefing: briefing('Rook', 'The decoy shook a carrier loose. It is slower than the scouts, bigger than a house, and rude enough to bring friends.'),
    debrief: debrief('The carrier fell into Iron Mesa and left a gate-frequency scar behind.', 'The carrier escaped and rejoined the fleet. Bring heavier fire and cut off the escorts.'),
    speakers: baseSpeakers,
    rewards: rewards(420),
    unlockText: 'Eclipse Field blackout mission unlocked.',
    radioEvents: [
      radio('m7-start', 'start', 'Rook', 'Carrier hunt', 'That big contact is not a cloud. Crack the escorts, then work the carrier.'),
      radio('m7-phase', 'bossPhase', 'Ops', 'Shield fracture', 'Carrier shield is buckling. Keep shells on target.', { phase: 1 }),
      radio('m7-low', 'hull', 'Vega', 'Hard beams', 'Carrier beam is chewing the hull. Break line and re-aim.', { below: 45 })
    ],
    worldSize: 148,
    ufoLimit: 86,
    cameraHeight: 30,
    cameraDistance: 43,
    sky: 0x20222a,
    fog: 0x796c62,
    fogDensity: 0.013,
    ground: 0x7b6b5a,
    groundDark: 0x4c443f,
    scrub: 0x4b6656,
    ridge: 0x3d3f43,
    accent: 0xd1b783,
    rocks: 72,
    cactus: 5,
    ridges: 26,
    extras: 'mesa',
    objectiveType: 'boss',
    objectiveScript: { bossType: 'carrier', bossHp: 8, escortKills: 7, bossSpawnDelay: 9 },
    destroyTarget: 8,
    ufoTotal: 11,
    maxActive: 3,
    spawnDelay: [1.45, 2.1],
    firstSpawn: 0.7,
    speed: [6.2, 8.6],
    altitude: [13, 23],
    drift: 2.1,
    hitAssist: 3,
    shellSpeed: 44,
    fireDelay: 0.21,
    beamDamage: 3.6,
    escapeDamage: 5.5,
    score: 340,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'raider', weight: 3 },
      { type: 'zigzag', weight: 3 },
      { type: 'shield', weight: 2 },
      { type: 'bomber', weight: 1 }
    ]
  },
  {
    id: 'eclipse-field',
    campaignIndex: 7,
    act: 'Act III: Gatefall',
    title: 'Mission 8: Eclipse Field',
    mapName: 'Eclipse Field',
    objective: 'Reactivate 4 blackout beacons and destroy 9 UFOs.',
    intro: 'Drive between beacon nodes and hold position to bring radar back online.',
    success: 'Blackout lifted. Command Line is visible again.',
    briefing: briefing('Echo', 'The gate scar blacked out our scopes. Four field beacons can punch through it, but each one needs a tank parked under the static.'),
    debrief: debrief('The blackout cracked. Command Line is under direct assault.', 'The blackout swallowed the beacons. We cannot defend what we cannot see.'),
    speakers: baseSpeakers,
    rewards: rewards(440),
    unlockText: 'Command Line defense unlocked.',
    radioEvents: [
      radio('m8-start', 'start', 'Echo', 'Beacon run', 'Hold near each beacon until it locks. The static will fight you.'),
      radio('m8-half', 'objective', 'Ops', 'Radar returning', 'Two beacons linked. Half the field is visible again.', { key: 'activateHalf' }),
      radio('m8-kills', 'kills', 'Rook', 'Static targets', 'They shimmer, but they still throw shadows.', { count: 5 })
    ],
    worldSize: 152,
    ufoLimit: 88,
    cameraHeight: 30,
    cameraDistance: 44,
    sky: 0x0c1118,
    fog: 0x202944,
    fogDensity: 0.018,
    ground: 0x444955,
    groundDark: 0x2f3443,
    scrub: 0x2f5f60,
    ridge: 0x202535,
    accent: 0x9fc7ff,
    rocks: 64,
    cactus: 0,
    ridges: 24,
    extras: 'eclipse',
    objectiveType: 'activate',
    objectiveScript: { nodes: 4, holdTime: 2.2, radius: 6, requireContinuous: true },
    destroyTarget: 9,
    ufoTotal: 13,
    maxActive: 3,
    spawnDelay: [1.35, 2],
    firstSpawn: 0.7,
    speed: [6.5, 9],
    altitude: [13, 23.5],
    drift: 2.3,
    hitAssist: 2.95,
    shellSpeed: 44,
    fireDelay: 0.21,
    beamDamage: 3.6,
    escapeDamage: 5.8,
    score: 350,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'zigzag', weight: 4 },
      { type: 'shield', weight: 3 },
      { type: 'raider', weight: 2 },
      { type: 'bomber', weight: 1 }
    ]
  },
  {
    id: 'command-line',
    campaignIndex: 8,
    act: 'Act III: Gatefall',
    title: 'Mission 9: Command Line',
    mapName: 'Command Line',
    objective: 'Protect Skybreak HQ and destroy 13 UFOs.',
    intro: 'A siege mission with multiple command towers and heavy bomber pressure.',
    success: 'Skybreak HQ held. The gate has nowhere left to hide.',
    briefing: briefing('Ops', 'They found Command Line. Every tower here is command, radar, and home. Hold the line long enough to triangulate the gate.'),
    debrief: debrief('Command Line held. Final coordinates are locked on the Mothership Gate.', 'Command Line fell silent. If HQ goes dark, the gate wins.'),
    speakers: baseSpeakers,
    rewards: rewards(500),
    unlockText: 'Mothership Gate final mission unlocked.',
    radioEvents: [
      radio('m9-start', 'start', 'Ops', 'Hold command', 'This is the line. Let nothing burn the command towers.'),
      radio('m9-seven', 'kills', 'Atlas', 'Siege thinning', 'Half their strike wing is down. Keep the towers alive.', { count: 7 }),
      radio('m9-tower', 'objective', 'Vega', 'HQ damage', 'Command tower is under direct beam fire.', { key: 'towerDamaged' })
    ],
    worldSize: 158,
    ufoLimit: 92,
    cameraHeight: 31,
    cameraDistance: 45,
    sky: 0x151b22,
    fog: 0x5f6d6e,
    fogDensity: 0.014,
    ground: 0x696959,
    groundDark: 0x42443c,
    scrub: 0x3d6455,
    ridge: 0x313738,
    accent: 0xf3bd55,
    rocks: 62,
    cactus: 6,
    ridges: 24,
    extras: 'command',
    objectiveType: 'protect',
    destroyTarget: 13,
    ufoTotal: 16,
    maxActive: 4,
    spawnDelay: [1.2, 1.8],
    firstSpawn: 0.55,
    speed: [6.8, 9.6],
    altitude: [13.5, 24],
    drift: 2.2,
    hitAssist: 2.75,
    shellSpeed: 45,
    fireDelay: 0.2,
    beamDamage: 3.85,
    towerDamage: 8.6,
    escapeDamage: 6.2,
    score: 370,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'raider', weight: 3 },
      { type: 'zigzag', weight: 3 },
      { type: 'bomber', weight: 3 },
      { type: 'shield', weight: 2 },
      { type: 'carrier', weight: 1 }
    ]
  },
  {
    id: 'mothership-gate',
    campaignIndex: 9,
    act: 'Act III: Gatefall',
    title: 'Mission 10: Mothership Gate',
    mapName: 'Mothership Gate',
    objective: 'Destroy 3 gate pylons and defeat the carrier finale.',
    intro: 'The final map is long, dense, and vertical. Break the pylons, then collapse the gate carrier.',
    success: 'Mothership gate collapsed. Skybreak is secure.',
    briefing: briefing('Ops', 'The gate is not a doorway. It is a cannon aimed at the sky. Break its pylons, bring down the carrier, and close Operation Skybreak.'),
    debrief: debrief('The gate collapsed in a blue-white flash over the ridge. For the first time in ten missions, radar is quiet.', 'The gate stabilized and the carrier held the line. Roll again before the cannon wakes.'),
    speakers: baseSpeakers,
    rewards: rewards(650),
    unlockText: 'Campaign complete. Free play timeline unlocked.',
    radioEvents: [
      radio('m10-start', 'start', 'Ops', 'Final gate', 'Break the pylons first. The carrier is feeding from them.'),
      radio('m10-pylons', 'objective', 'Echo', 'Gate exposed', 'Pylons are down. The carrier shield is starving.', { key: 'collectAll' }),
      radio('m10-phase', 'bossPhase', 'Rook', 'Finish it', 'Carrier core is exposed. Put the last shells into the glow.', { phase: 1 })
    ],
    worldSize: 164,
    ufoLimit: 94,
    cameraHeight: 31,
    cameraDistance: 46,
    sky: 0x0e141e,
    fog: 0x202544,
    fogDensity: 0.014,
    ground: 0x4f535c,
    groundDark: 0x303846,
    scrub: 0x315565,
    ridge: 0x20283a,
    accent: 0x9fc7ff,
    rocks: 70,
    cactus: 0,
    ridges: 28,
    extras: 'gate',
    objectiveType: 'boss',
    objectiveScript: { pylons: 3, pylonRadius: 4.8, bossType: 'carrier', bossHp: 10, escortKills: 8, bossSpawnDelay: 10 },
    destroyTarget: 15,
    survivalTime: 110,
    ufoTotal: 18,
    maxActive: 4,
    spawnDelay: [1.15, 1.8],
    firstSpawn: 0.65,
    speed: [6.6, 9.4],
    altitude: [14, 24],
    drift: 2.25,
    hitAssist: 2.8,
    shellSpeed: 44,
    fireDelay: 0.21,
    beamDamage: 3.8,
    escapeDamage: 6,
    score: 390,
    maxUfoHp: 2,
    ufoMix: [
      { type: 'raider', weight: 3 },
      { type: 'zigzag', weight: 3 },
      { type: 'shield', weight: 2 },
      { type: 'bomber', weight: 2 },
      { type: 'carrier', weight: 1 }
    ]
  }
];
